services:
  db:
    image: postgres:latest
    container_name: pern-open-library-postgres
    restart: always
    env_file:
      - ./server/src/configs/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: server
    image: virezee/pern-open-library-backend:latest
    container_name: pern-open-library-express
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - db
  frontend:
    build: client
    image: virezee/pern-open-library-frontend:latest
    container_name: pern-open-library-react
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
volumes:
  pg_data: