services:
  backend:
    build: server
    container_name: express
    env_file:
      - ./server/src/configs/.env
    ports:
      - 3001:3001
  frontend:
    build: client
    container_name: react
    env_file:
      - ./client/.env
    ports:
      - 3000:3000