services:
  db:
    image: postgres:latest
    container_name: pern-open-library-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: server
    container_name: pern-open-library-express
    env_file:
      - ./server/src/configs/.env
    ports:
      - 3001:3001
    depends_on:
      - db
  frontend:
    build: client
    container_name: pern-open-library-react
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    depends_on:
      - backend
volumes:
  pg_data: